# Generated by Django 4.0.3 on 2022-10-28 19:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('student', '0003_alter_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=50)),
                ('Course_dept', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('Quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quiz_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('Quiz_Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
                ('Quiz_Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('Result_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail')], default=0, max_length=50)),
                ('Quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('neg_marks', models.IntegerField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correct_option', models.IntegerField()),
                ('Question_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
