# Generated by Django 4.0.3 on 2022-11-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='Question_desc',
        ),
    ]
