# Generated by Django 4.0.3 on 2022-10-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=0, max_length=200)),
                ('Username', models.CharField(default=0, max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Pass', models.CharField(max_length=200)),
            ],
        ),
    ]
