# Generated by Django 4.0.3 on 2022-10-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Dept', models.CharField(default='', max_length=70)),
                ('pass1', models.CharField(default='', max_length=70)),
                ('pass2', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
    ]
