# Generated by Django 4.0.3 on 2022-10-26 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Dob',
            field=models.DateField(default=datetime.datetime(2022, 10, 27, 0, 44, 6, 805392)),
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Year',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=0),
        ),
    ]
