# Generated by Django 4.0.3 on 2022-10-28 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_dob_student_gender_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Dob',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
